env_name: "door-open-v2"
env_task: "single-env"
exp_name: "door-open-v2"
observation_type: "image_joints"
seed: 42

# Logging
logger: wandb
mode: online
entity: neuropioneers

image_size: 64
from_pixels: 1

# training
max_steps: 55000
batch_size: 256

actor_dropout: 0.1

save_path: "./ckpts"
ckpt_interval: 40000

