env_name: "door-open-v2"
env_library: gym
exp_name: "${env_name}"
observation_type: "image_joints"
seed: 42
async_collection: 1
record_video: 0
frame_skip: 1

# Updates
utd_ratio: 1.0
batch_size: 256
lr: 3e-4
weight_decay: 0.0
target_update_polyak: 0.995
multi_step: 1.0
gamma: 0.99
max_steps: 110000
eval_interval: 1000
save_interval: 25000
save_path: "/home/mohan/work/research/bdreamm/saved_models/meta_world_checkpoints/${env_name}"
actor_dropout: 0.1
critic_dropout: 0.0
value_dropout: 0.0

tanh_loc: False
default_policy_scale: 1.0
scale_lb: 0.1
activation: elu
from_pixels: 1
#collector_devices: [cuda:1,cuda:1,cuda:1,cuda:1]
collector_devices: [cpu]
env_per_collector: 10
frames_per_batch: 1000 # 5*200
max_frames_per_traj: 280
num_workers: 4

image_size: 64

record_frames: 10000
loss_function: smooth_l1
batch_transform: 1
buffer_prefetch: 64
norm_stats: 1

device: "cuda:0"

# IQL hyperparameter
temperature: 0.5
expectile: 0.7

# Logging
logger: wandb
mode: online
entity: neuropioneers


envs:
  a: "door-open-v2"
  b: "drawer-close-v2"
  c: "drawer-open-v2"
  d: "button-press-topdown-v2"
  e: "window-open-v2"
  f: "window-close-v2"
  g: "reach-v2"
